### ISSUE TITLE
Istanbul throws when pitching loader is used

### ISSUE THREAD

**Issue by kpdecker** [webpack-contrib/istanbul-instrumenter-loader#3]
When using a pitching loader such as:
https://github.com/walmartlabs/circus-handlebars#programatically-loading-modules
https://github.com/walmartlabs/circus-handlebars/blob/master/lib/loaders/helper.js

Istanbul fails to report coverage properly due to `resourcePath` having the same value for both the original request, `require('helper!foo')`, and the request made by the pitching loader, `require('!foo')`.

I could not find a way to generically prevent the coverage tool from running on the code emitted by the pitching loader and had to use `require('!!helper!foo')` to fix the coverage reporting.

**Comment by kpdecker** [comment]
Error thrown on the client:
```
ERROR [coverage]: [TypeError: Cannot read property 'start' of undefined]
TypeError: Cannot read property 'start' of undefined
  at pack/node_modules/istanbul/lib/object-utils.js:62:44
  at Array.forEach (native)
  at Object.addDerivedInfoForFile (pack/node_modules/istanbul/lib/object-utils.js:58:37)
  at Object.Collector.fileCoverageFor (pack/node_modules/istanbul/lib/collector.js:94:15)
  at pack/node_modules/istanbul/lib/report/html.js:523:90
  at Array.forEach (native)
  at HtmlReport.Report.mix.writeReport (pack/node_modules/istanbul/lib/report/html.js:522:27)
  at pack/node_modules/karma-coverage/lib/reporter.js:138:24
  at pack/node_modules/karma/lib/helper.js:87:7
  at Object.oncomplete (fs.js:107:15)
```

**Comment by kpdecker** [comment]
https://github.com/kpdecker/istanbul-instrumenter-loader/commit/18bd727cd44fa1057e3d5114b8219f79cf5573fb has a fix for this which I can PR if this is desired. I'm not 100% in love with it but it is safe for my team's use case.

**Comment by sokra** [comment]
Even without pitching loaders it's possible that multiple modules have the same `resourcePath`. i. e.

``` js
require("./a");
require("raw!./a");
```

**Comment by nkbt** [comment]
@sokra so is there any way to fix it? I have the same issue but using inject-loader. So one module is included twice. One time as `require("inject!my-module")({some: thing})` and another time as `require("my-module")` somewhere in a different test.

I temporarily fixed it by not including the module in one place. But that is not a real solution.

Any suggestion where this should be addressed? Here? Webpack? Istanbul?

PS: I spent some time hacking and patching Istanbul itself to ignore these issues, but did not get any acceptable results within couple of hours that I could spend on that.

**Comment by sokra** [comment]
It's wrong to use `this.resourcePath` because it is not unique. `this.request` is unique.

If you want it to look more pretty maybe `this.resourcePath + " (" + this.request + ")"` or `this.resourcePath + "?" + hashOf(this.request)`.

**Comment by nkbt** [comment]
Thanks, that makes sense. I'll check tomorrow if it works for my case

**Comment by jcreamer898** [comment]
Was there ever any progress made here? I'm seeing this issue using the `inject-loader` right now in one of my tests.

![](http://d.pr/i/rK8w+)

**Comment by mijay** [comment]
I worked around this issue by adding istanbul-instrumenter as a normal loader in (test-specific) webpack.config, not as a pre/postLoader.

**Comment by nkbt** [comment]
Interesting! Thanks, Dmitry, for sharing

**Comment by kgentes** [comment]
I have this issue as well. Reading through the thread it appears people are doing different things to resolve it.  I am loath to add one of these "workarounds" if a fix is actually immanent.

Any advice from those in the "know" as to the best approach here?

**Comment by kgentes** [comment]
Does anyone have a good workaround for this issue?  It's really breaking my builds at this point. The only thing I can do right now is drop back to 0.2.0 which doesn't crash like this. But at that point, it can't do Typescript so the code coverage is displayed in Javascript which is pretty much unhelpful.

If you have a working workaround, can you please post it.

This issue has basically hamstrung this package to be unusable for anyone doing Typescript, since this error is produced:
```
07 02 2017 12:09:07.782:ERROR [coverage]: TypeError: Cannot read property 'text' of undefined
    at C:\git\myproject\node_modules\istanbul\lib\report\html.js:239:51
    at Array.forEach (native)
    at annotateFunctions (C:\git\myproject\node_modules\istanbul\lib\report\html.js:224:26)
    at HtmlReport.writeDetailPage (C:\git\myproject\node_modules\istanbul\lib\report\html.js:427:9)
    at C:\git\myproject\node_modules\istanbul\lib\report\html.js:489:26
    at SyncFileWriter.writeFile (C:\git\myproject\node_modules\istanbul\lib\util\file-writer.js:57:9)
    at FileWriter.writeFile (C:\git\myproject\node_modules\istanbul\lib\util\file-writer.js:147:23)
    at C:\git\myproject\node_modules\istanbul\lib\report\html.js:488:24
    at Array.forEach (native)
    at HtmlReport.writeFiles (C:\git\myproject\node_modules\istanbul\lib\report\html.js:482:23)
    at C:\git\myproject\node_modules\istanbul\lib\report\html.js:484:22
    at Array.forEach (native)
    at HtmlReport.writeFiles (C:\git\myproject\node_modules\istanbul\lib\report\html.js:482:23)
    at HtmlReport.writeReport (C:\git\myproject\node_modules\istanbul\lib\report\html.js:56

```

thank you.

**Comment by carlos-** [comment]
@kgentes, @mattlewis92 built this karma plugin: [karma-coverage-istanbul-reporter](https://github.com/mattlewis92/karma-coverage-istanbul-reporter). It is now working for me.

**Comment by deepsweet** [comment]
can't believe we can close this...

**Comment by deepsweet** [comment]
https://github.com/deepsweet/istanbul-instrumenter-loader/issues/48

**Comment by mattlewis92** [comment]
As all of the stack traces are coming from the old `karma-coverage` reporter, I believe that using the `karma-coverage-istanbul-reporter` reporter should fix this problem: https://github.com/webpack-contrib/istanbul-instrumenter-loader/issues/3#issuecomment-278608076 As a result I'm going to close this for now, if you're still experiencing this even with the `karma-coverage-istanbul-reporter` then please let me know and I'd be happy to dig in more and try and fix it 😄
