### ISSUE TITLE
strange bug I just can pin a description to

### ISSUE THREAD

**Issue by shlomiassaf** [webpack-contrib/istanbul-instrumenter-loader#38]
When trying to upgrade [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter) (PR AngularClass/angular2-webpack-starter#1297) to **istanbul-instrumenter-loader@1.2.0** there's a strange bug...

It happens when using a specific angular configuration to set an import in an `NgModule`.

When doing so the test breaks, removing `istanbul-instrumenter-loader` (or reverting back to 0.2.0) removes the issue.

To me it smells like the metadata, the loader might remove some of the metadata of a type when it's not directly used.. I don't know :)

To reproduce clone the repo then update to 1.2.0 and add the code in AngularClass/angular2-webpack-starter#1309

You can look at the issue for some more information.

I'm sorry for lack of information, this is an area i'm not the best in...

**Comment by mattlewis92** [comment]
It looks like that starter [has been upgraded](https://github.com/AngularClass/angular-starter/blob/master/package.json#L118) to the latest version of this loader so I think this can be closed now 😄
