### ISSUE TITLE
MAINTAINER NEEDED

### ISSUE THREAD

**Issue by deepsweet** [webpack-contrib/istanbul-instrumenter-loader#48]

**Comment by Axbon** [comment]
I'd be happy to help fixing the jsx, but not really sure where to start here :). It doesn't happen to be easier to migrate babel-istanbul-loader to work with webpack 2 rather than adding jsx support here? In terms of amount of effort.

**Comment by d3viant0ne** [comment]
@deepsweet - I'm one of the admins for https://github.com/webpack-contrib

We can transfer this over into the org if maintenance is an issue, if you are interested we can discuss the particulars on gitter.

**Comment by deepsweet** [comment]
@d3viant0ne hey, sure I want to transfer it. I'm not using this loader anymore so it becomes difficult to maintain it. what do you need from my side?

**Comment by d3viant0ne** [comment]
@deepsweet - Webpack & webpack-contrib are both apart of the JS Foundation, so there is a bit of process that needs to be followed but nothing terribly cumbersome.

I'll get the process started on our end.

**Comment by d3viant0ne** [comment]
@deepsweet - See #49 

Outside of that, @d3viant0ne & @bebraw need to be set as owners in npm.

`npm add owner bebraw` and `npm add owner d3viant0ne`

The only other remaining question is do you want to retain access as a maintainer or just hand this off entirely. That is completely up to you and we can always add you back later should you opt to just hand it off.

Once the license file & npm owners are setup, let me know if you want to continue to maintain in a limited fashion & then initiate the transfer to me ( can't transfer directly to an org ) and I will then transfer this into `webpack-contrib` & either get your permissions setup or not depending on the above.

There are a few other standards / documentation updates that will happen but that's for me to do once it's transferred.

**Comment by deepsweet** [comment]
license has been changed, NPM owners were added.

yes, I want to continue to maintain this "in a limited fashion" on some critical issues where descent knowledge about how code coverage works is required.

transferring this repo to you.

**Comment by d3viant0ne** [comment]
Alright, i'll get your access set again as soon as I transfer it into contrib & get you a slack invite

**Comment by bebraw** [comment]
Slack invite done.
