### ISSUE TITLE
Wrong coverage output

### ISSUE THREAD

**Issue by mickske** [webpack-contrib/istanbul-instrumenter-loader#60]
I see some weird coverage report output.

this is my karma.conf:
```javascript
config.set({
        frameworks: [
            'mocha',
            'chai',
            'sinon'
        ],

        client: {
            mocha: {
                reporter: 'html',
                ui: 'bdd'
            }
        },

        files: [
            './WebContent/webappsTest/tests.webpack.js'
        ],

        autoWatch: true,

        browsers: [
            'PhantomJS'
        ],

        preprocessors: {
            './WebContent/webappsTest/tests.webpack.js': ['webpack', 'sourcemap']
        },

        reporters: [
            'progress',
            'mocha',
            'coverage-istanbul'
        ],

        coverageIstanbulReporter: {
            reports: [ 'html', 'text-summary' ],
            fixWebpackSourcePaths: true
        },

        webpack: {
            devtool: 'inline-source-map',
            stats: false,
            module: {
                rules: [
                    {
                        test: /\.js$/,
                        include: path.resolve('WebContent/webapps/'),
                        exclude: '/node_modules/',
                        loader: 'istanbul-instrumenter-loader',
                        options: { esModules : true }
                    },
                    {
                        test: /\.js$/,
                        exclude: '/node_modules/',
                        loader: 'babel-loader',
                        options: {
                            presets: [
                                ['es2015', {modules: false}]
                            ]
                        }
                    }
                ]
            }
        },

        plugins: [
            'karma-webpack',
            'karma-mocha',
            'karma-mocha-reporter',
            'karma-chai',
            'karma-sinon',
            'karma-phantomjs-launcher',
            'karma-chrome-launcher',
            'karma-coverage-istanbul-reporter',
            'karma-sourcemap-loader'
        ]

    });
```

Now everything works and runs fine, my tests are being executed and my report is being generated but even without zero test cases written my code coverage comes back with certain amount of coverage, which i expected should be 0% since i'm not running a single test case on it.

![image](https://user-images.githubusercontent.com/7976119/27292856-a16c6e90-54e2-11e7-8b26-dc0c19874705.png)

My test file looks like this:
```javascript
const testsContext = require.context('./', true, /\.test\.js$/);
testsContext.keys().forEach(testsContext);

const componentsContext = require.context('../webapps/', true, /\.js$/);
componentsContext.keys().forEach(componentsContext);
```

Anything obvious that i'm doing wrong here?

Also what i'm seeing is that my test files are being loaded into the coverage report, if i'm not mistaken they shouldn't be there is that correct?

Thanks

**Comment by mattlewis92** [comment]
This is expected behaviour as when you include the source files in your test file, anything in the top level scope of each module will be executed and hence appear as ran in the coverage report. If you open up the html report for each of those files you'll probably see something that correlates to this.  If you don't want this behaviour then you would need to remove
```
const testsContext = require.context('./', true, /\.test\.js$/);
testsContext.keys().forEach(testsContext);

const componentsContext = require.context('../webapps/', true, /\.js$/);
componentsContext.keys().forEach(componentsContext);
``` 

and instead have each spec file manually include the source file that it executes.

In order to exclude test files from appearing in the reports you need to not instrument them by not passing them to this loader. Assuming your test files follow a convention that they end in `.spec.js` you can use a regex like `exclude: /(node_modules|\.spec\.js$)/,` in the loader config, to exclude them from the report. Hope that helps! 😄
