### ISSUE TITLE
Make babel as peerDependencies

### ISSUE THREAD

**Issue by ssavajols** [webpack-contrib/istanbul-instrumenter-loader#72]
Please, can you remove babel from dependencies  ? 

It cause errors when babel was at a lower version if we update istanbul-intrumenter-loader to V3.

It's not absolutly required to have babel 7 to get this work and it is not the responsibility of instanbul to provide the babel version to the projet I think.

**Comment by michael-ciniawsky** [comment]
Can you elaborate where`babel` causes issues and where it is used? Do you mean from `devDependencies`
