### ISSUE TITLE
Plans for upgrading version of loader-utils?

### ISSUE THREAD

**Issue by johnlacr** [webpack-contrib/istanbul-instrumenter-loader#81]
We recently upgraded our project to angular 5 and when we run ng test with code coverage we are getting the parseQuery() webpack deprecation warning: https://github.com/webpack/loader-utils/issues/56.

Are there any plans to update the version of loader-utils being used by instanbul-instrumenter-loader?

**Comment by evilebottnawi** [comment]
@johnlacr yes, in this PR https://github.com/webpack-contrib/istanbul-instrumenter-loader/pull/79. Thank for issue!
