### ISSUE TITLE
v3.0.1 is not published on npm

### ISSUE THREAD

**Issue by jgerigmeyer** [webpack-contrib/istanbul-instrumenter-loader#85]
It appears that the `v3.0.1` release was never published to npm:

```
$ npm info istanbul-instrumenter-loader
```

```
{ name: 'istanbul-instrumenter-loader',
  description: 'Istanbul instrumenter loader for webpack',
  'dist-tags': { latest: '3.0.0', beta: '3.0.0-rc.1' },
  versions:
   [ '0.1.0',
     '0.1.1',
     '0.1.2',
     '0.1.3',
     '0.2.0',
     '1.0.0',
     '1.1.0',
     '1.2.0',
     '2.0.0',
     '3.0.0-beta.0',
     '3.0.0-beta.1',
     '3.0.0-rc.0',
     '3.0.0-rc.1',
     '3.0.0' ],
  ...
```

**Comment by michael-ciniawsky** [comment]
Yep, I realized after `git push --follow-tags ... && npm publish` that I don't have `npm` access to this package and therefore it's on `master` but not published yet ¯\_(ツ)_/¯. I pinged folks but no response there either yet...

**Comment by mtraynham** [comment]
@michael-ciniawsky any updates on this?  publish to a new name?

**Comment by astorije** [comment]
v3.0.1 is now available: https://www.npmjs.com/package/istanbul-instrumenter-loader?activeTab=versions
So I believe this issue can be closed :)
